name: Check for new forecasts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-flight-delays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --deploy --ignore-pipfile

      - name: Run script
        run: pipenv run python scrape.py > output.log
          tail -n 10 output.log

      - name: Commit and push if csv changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add spot_forecasts.csv
          git diff --cached --quiet || (git commit -m "Update forecasts csv" && git push)